gpu 변경 확인

In [2]:
import torch
print(torch.__version__)
print("GPU 사용가능 :", torch.cuda.is_available())

2.9.0+cu128
GPU 사용가능 : True


텐서 생성 실습

In [4]:
x = torch.tensor([[1, 2], [3, 4]])
print(x)
print(x.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


3x3랜덤 텐서 만들기

In [15]:
import torch
x = torch.rand(3, 3)
print(x)
print(x.shape)

tensor([[0.0974, 0.7712, 0.9255],
        [0.5161, 0.6931, 0.0188],
        [0.5130, 0.3567, 0.9536]])
torch.Size([3, 3])


torch.randint 사용

In [17]:
x = torch.randint(1,10, (3, 3))
print(x)
print(x.shape)

tensor([[7, 7, 6],
        [7, 3, 7],
        [9, 4, 2]])
torch.Size([3, 3])


평균값 구하기

In [29]:
x = torch.randint(1, 100,(5, 5))
print(x)
print(x.shape)
avg = x.float().mean()
print(f"평균값: {avg:.2f}")

tensor([[14, 77, 20, 56, 61],
        [84, 48, 22, 69, 54],
        [19, 57, 69, 18, 61],
        [30,  3, 40, 33, 69],
        [29,  9, 60,  2, 76]])
torch.Size([5, 5])
평균값: 43.20


텐서 연산

In [30]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
print(a+b)
print(a*b)
print(torch.dot(a, b))

tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor(32.)


행렬 곱 사용하기(torch.matmul)

In [43]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
print(torch.matmul(a, b))

tensor(32.)


텐서 reshape 하기

In [51]:
a = torch.tensor([[1., 2.],
                 [4., 7.],
                 [6., 2.]])
print(a.shape)
A = a.reshape((2,3))
print(A.shape)
print(A)

torch.Size([3, 2])
torch.Size([2, 3])
tensor([[1., 2., 4.],
        [7., 6., 2.]])


GPU로 옮기기

In [59]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.randn(3, 3).to(device)
print(x.device)

cuda:0


In [58]:
print(torch.cuda.is_available())

True


to(device) 없이 실행하면 어떤 에러가 나는지 확인

In [61]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.randn(3, 3)
print(x.device)

cpu


자동미분 (Gradient)

In [63]:
x = torch.tensor(2.0, requires_grad=True)
y = x**2
y.backward()
print("gradient :", x.grad)

gradient : tensor(4.)


x=3 일 때 미분값 확인

In [65]:
x = torch.tensor(3.0, requires_grad=True)
y= x**2
y.backward()
print("gradient : ", x.grad)

gradient :  tensor(6.)


y=x**3 으로 바꿔보기

In [66]:
x = torch.tensor(2.0, requires_grad=True)
y = x**3
y.backward()
print("gradient :", x.grad)

gradient : tensor(12.)


In [67]:
x = torch.tensor(3.0, requires_grad=True)
y = x**3
y.backward()
print("gradient :", x.grad)

gradient : tensor(27.)


간단한 함수 미분

In [68]:
x = torch.tensor(1.0, requires_grad=True)
y = 3*x**2 + 2*x + 1
y.backward()
print(x.grad)

tensor(8.)


간단한 선형모델 만들기

In [69]:
import torch.nn as nn
model = nn.Linear(1,1)
print(model.weight)

Parameter containing:
tensor([[-0.3669]], requires_grad=True)


nn은 신경망 만들때 쓰는 모듈
nn.Linear(1,1) => 선형모델 하나 만드는 것(y=Wx+b)

(1, 1) : 입력차원, 출력차원: x하나를 받아서 y 하나를 출력


랜덤 입력 넣기

In [80]:
import torch.nn as nn
model = nn.Linear(1,1)
x = torch.randn(1,1)
y = model(x)
print(model.weight)

Parameter containing:
tensor([[0.7994]], requires_grad=True)


선형회귀 맛보기

In [83]:
import torch.optim as optim
model = nn.Linear(1,1)
optimizer = optim.SGD(model.parameters(), lr=0.01)

x = torch.tensor([[1.0], [2.0], [3.0]])
y = torch.tensor([[3.0],[4.0], [5.0]])

for epoch in range(100):
  pred = model(x)
  loss =((pred - y)**2).mean()

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  print(model.weight, model.bias)

Parameter containing:
tensor([[0.0859]], requires_grad=True) Parameter containing:
tensor([0.8241], requires_grad=True)
Parameter containing:
tensor([[0.2183]], requires_grad=True) Parameter containing:
tensor([0.8842], requires_grad=True)
Parameter containing:
tensor([[0.3359]], requires_grad=True) Parameter containing:
tensor([0.9378], requires_grad=True)
Parameter containing:
tensor([[0.4404]], requires_grad=True) Parameter containing:
tensor([0.9856], requires_grad=True)
Parameter containing:
tensor([[0.5332]], requires_grad=True) Parameter containing:
tensor([1.0282], requires_grad=True)
Parameter containing:
tensor([[0.6156]], requires_grad=True) Parameter containing:
tensor([1.0663], requires_grad=True)
Parameter containing:
tensor([[0.6888]], requires_grad=True) Parameter containing:
tensor([1.1004], requires_grad=True)
Parameter containing:
tensor([[0.7539]], requires_grad=True) Parameter containing:
tensor([1.1308], requires_grad=True)
Parameter containing:
tensor([[0.8116]],