<a href="https://colab.research.google.com/github/ssoyyoungg/practice/blob/main/pytorch_auto_preview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

차원 맞추기 실습

dim=0 : 세로방향 축 제거

dim=1 : 가로방향 축 제거

In [40]:
import torch

x = torch.randn(5, 3)
print("원래 shape :", x.shape)

print("mean(dim=0) : ", x.mean(dim=0).shape)
print("mean(dim=1) : ", x.mean(dim=1).shape)

원래 shape : torch.Size([5, 3])
mean(dim=0) :  torch.Size([3])
mean(dim=1) :  torch.Size([5])


reshape/view 사용

In [41]:
x = torch.randn(2, 3, 4)
print(x.shape)
y = x.view(2, -1)
print(y.shape)

torch.Size([2, 3, 4])
torch.Size([2, 12])


reshape/view 사용(2)

In [42]:
x = torch.randn(4,3,5)
print(x.shape)
y = x.view(4, -1)
print(y.shape)


torch.Size([4, 3, 5])
torch.Size([4, 15])


Gradient 실습

 3x + 1를 미분 하면 => 3

      3 * x^1 =>
      3 * 1 * x^0 =>
      3 * 1 * 1 => 3
 상수는 미분하면 사라짐

In [43]:
x = torch.tensor(3.0, requires_grad=True)
y = 2*x**2 + 3*x + 1
y.backward()

print(x.grad)

tensor(15.)


gradient 초기화 안하면 생기는 일

초기화 안하면 앞선 결과 값을 더해버림

초기화 하는 방법 :
x.grad.zero_() 넣기

In [44]:
x = torch. tensor(2.0, requires_grad=True)

y1 = x**2
y1.backward()
print("첫번째 : ", x.grad)

y2 = x**3
y2.backward()
print("두번째 : ", x.grad)


첫번째 :  tensor(4.)
두번째 :  tensor(16.)


Linear를 수학과 연결

In [45]:
import torch.nn as nn

model = nn.Linear(2,1)

x = torch.tensor([1.0, 2.0])
y = model(x)

print("weight : ", model.weight)
print("bias : ", model.bias)
print("ouput : ", y)

weight :  Parameter containing:
tensor([[ 0.4304, -0.0414]], requires_grad=True)
bias :  Parameter containing:
tensor([-0.4615], requires_grad=True)
ouput :  tensor([-0.1139], grad_fn=<ViewBackward0>)


학습 루프 총집합

In [46]:
model = nn.Linear(1, 1)
optimizer =torch.optim.SGD(model.parameters(), lr=0.1)

x = torch.tensor([[1.0], [2.0], [3.0]])
y = torch.tensor([[3.0], [4.0], [5.0]])

for epoch in range(10):
  pred = model(x)
  loss = ((pred-y)**2).mean()

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  print(epoch, loss.item())

0 22.60467529296875
1 0.5196437239646912
2 0.24397683143615723
3 0.2293897420167923
4 0.21845771372318268
5 0.2080804854631424
6 0.19819647073745728
7 0.18878202140331268
8 0.17981481552124023
9 0.17127329111099243


In [47]:
print(model.weight.data)
print(model.bias.data)

tensor([[1.4691]])
tensor([0.9336])


model = nn.Linear(1, 1)

: 입력 1개 출력 1개

optimizer =torch.optim.SGD(model.parameters(), lr=0.1)

: 옵티마이저 설정, 경사하강법, 학습속도 0.1

for epoch in range(10):
  pred = model(x)
  loss = ((pred-y)**2).mean()

: 학습 10번동안

모델(x)를 pred(예측값)에 대입

손실률 제곱함 (음수는 없애고 계산을 매끄럽게 만들기 위함)


optimizer.zero_grad()

누적되서 계산되지 않게 함
  
  loss.backward()

손실율 역전파로 계산 활성화
  
  optimizer.step()

가중치 업데이트

에러 생성 해보기

In [48]:
x = torch.tensor([1.0, 2.0])
model(x)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 1x1)

위에서 선언한 모델은 (1, 1)

내가 입력한 데이터는 2개의 데이터임 그래서 오류가 남




CPU와 GPU 섞어보기

In [50]:
device = torch.device("cuda")
x = torch.randn(3, 3). to(device)

y = torch.randn(3, 3)

x+y

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

CPU와 GPU의 저장위치가 다르기 때문에 에러가 남

배운것을 토대로 직접 코드 구현

In [64]:
x = torch.linspace(-5, 5, 50).view(-1, 1)
y = 5*x -3
print(x.shape)
print(y.shape)
for epoch in range(100):
  pred = model(x)
  loss = ((pred-y)**2).mean()
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  print(epoch, loss.item())
  print(model.weight.data)
  print(model.bias.data)

torch.Size([50, 1])
torch.Size([50, 1])
0 3.017532838184289e-12
tensor([[5.0000]])
tensor([-3.0000])
1 2.1580604057241937e-12
tensor([[5.0000]])
tensor([-3.0000])
2 3.017532838184289e-12
tensor([[5.0000]])
tensor([-3.0000])
3 2.1580604057241937e-12
tensor([[5.0000]])
tensor([-3.0000])
4 3.017532838184289e-12
tensor([[5.0000]])
tensor([-3.0000])
5 2.1580604057241937e-12
tensor([[5.0000]])
tensor([-3.0000])
6 3.017532838184289e-12
tensor([[5.0000]])
tensor([-3.0000])
7 2.1580604057241937e-12
tensor([[5.0000]])
tensor([-3.0000])
8 3.017532838184289e-12
tensor([[5.0000]])
tensor([-3.0000])
9 2.1580604057241937e-12
tensor([[5.0000]])
tensor([-3.0000])
10 3.017532838184289e-12
tensor([[5.0000]])
tensor([-3.0000])
11 2.1580604057241937e-12
tensor([[5.0000]])
tensor([-3.0000])
12 3.017532838184289e-12
tensor([[5.0000]])
tensor([-3.0000])
13 2.1580604057241937e-12
tensor([[5.0000]])
tensor([-3.0000])
14 3.017532838184289e-12
tensor([[5.0000]])
tensor([-3.0000])
15 2.1580604057241937e-12
tensor(

limspace : 원하는 시작점과 끝점에 해당하는 구역에 대해 동일한 간격으로 특정 갯수만큼 벡터를 생성하는 것

1️⃣ Linear는 무엇인가?

입력 숫자들을 섞어서 새로운 숫자를 만드는 것

2️⃣ weight shape는 왜 (out, in)인가?

입력값과 출력값이 동일해야 하기

3️⃣ mean(dim=0)는 무엇을 의미하는가?

세로축 평균

4️⃣ backward는 무엇을 계산하는가?

gradient를 자동으로 계산함

5️⃣ optimizer.step은 무엇을 바꾸는가?

gradient를 이용해서 weight(가중치)를 업데이트 함